### PR TITLE
Aligned to changes in oM - moving Reflection_oM objects to Base_oM plus IFCSettings to inherit from BHoMObject

### LINKED ISSUE #15: Align to changes in oM - moving Reflection_oM objects to Base_oM
#### Description:

Following the changes introduced by https://github.com/BHoM/BHoM/pull/1339, the code of IFC_Toolkit needs to be aligned.

### LINKED ISSUE #17: IFCSettings does not inherit from BHoMObject
#### Description:

As in the title: this causes the autogenerated constructor not appear in the UIs.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #15
Closes #17 

### Test files

#15: one of the files from [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FIFC%5FToolkit&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) should be fine.
#17: run GH and check if the autogenerated constructor is available through the UI.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by FraserGreenroyd — APPROVED** [review]
All changes reviewed by code review ones which implement the changes from oM/Engine, plus the mentioned settings inheriting from BHoMObject.

The new file is code moved from another file, so am happy there's no functionality changes in this PR, just alignment.

**Pull request merged**
